In [32]:
import pandas as pd

In [33]:
alphabet = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
count_per_letter_cam = [*range(1,41)]

print(count_per_letter_cam)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [34]:
image_names = []
for letter in alphabet:
    for number in count_per_letter_cam:
        image_names.append(f'Below_{letter} ({number})')
        image_names.append(f'Front_{letter} ({number})')
        image_names.append(f'Left_{letter} ({number})')
        image_names.append(f'Right_{letter} ({number})')
        
len(image_names)

4160

In [35]:
image_values = []
for i in image_names:
    for letter in alphabet:
        if f'_{letter}' in i:
            image_values.append(letter)
            
len(image_values)

4160

In [41]:
values_df = pd.DataFrame({'Image Name':image_names,'Image Value':image_values})

values_df.tail(50)

        Image Name Image Value
4110   Left_Z (28)           Z
4111  Right_Z (28)           Z
4112  Below_Z (29)           Z
4113  Front_Z (29)           Z
4114   Left_Z (29)           Z
4115  Right_Z (29)           Z
4116  Below_Z (30)           Z
4117  Front_Z (30)           Z
4118   Left_Z (30)           Z
4119  Right_Z (30)           Z
4120  Below_Z (31)           Z
4121  Front_Z (31)           Z
4122   Left_Z (31)           Z
4123  Right_Z (31)           Z
4124  Below_Z (32)           Z
4125  Front_Z (32)           Z
4126   Left_Z (32)           Z
4127  Right_Z (32)           Z
4128  Below_Z (33)           Z
4129  Front_Z (33)           Z
4130   Left_Z (33)           Z
4131  Right_Z (33)           Z
4132  Below_Z (34)           Z
4133  Front_Z (34)           Z
4134   Left_Z (34)           Z
4135  Right_Z (34)           Z
4136  Below_Z (35)           Z
4137  Front_Z (35)           Z
4138   Left_Z (35)           Z
4139  Right_Z (35)           Z
4140  Below_Z (36)           Z
4141  Front_Z (36)           Z
4142   Left_Z (36)           Z
4143  Right_Z (36)           Z
4144  Below_Z (37)           Z
4145  Front_Z (37)           Z
4146   Left_Z (37)           Z
4147  Right_Z (37)           Z
4148  Below_Z (38)           Z
4149  Front_Z (38)           Z
4150   Left_Z (38)           Z
4151  Right_Z (38)           Z
4152  Below_Z (39)           Z
4153  Front_Z (39)           Z
4154   Left_Z (39)           Z
4155  Right_Z (39)           Z
4156  Below_Z (40)           Z
4157  Front_Z (40)           Z
4158   Left_Z (40)           Z
4159  Right_Z (40)           Z

In [43]:
values_df.to_csv('Image Values.csv')